apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forecast-ingress
  namespace: demand-forecast
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: forecast.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: forecast-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forecast-dashboard
                port:
                  number: 8501
